### ISSUE TITLE
Add the Latin American countries

### ISSUE THREAD

**Issue by YordanSoares** [rocklobster-in/listo#1]
In this issue I will report pull requests related to the submission of the lists of subdivisions from the following Latin American countries:

- 🇦🇷 **Argentina** (Done: #4)
- 🇧🇴 **Bolivia** (Done: #6)
- 🇧🇷 **Brazil** (Done: #5)
- 🇨🇱 **Chile** (Done: #7)
- 🇨🇴 **Colombia** (Done: #8)
- 🇨🇷  **Costa Rica** (Done: #9)
- 🇨🇺 **Cuba** (Done: #10)
- 🇪🇨 **Ecuador** (Done: #11)
- 🇸🇻 **El Salvador** (Done: #12)
- 🇬🇹 **Guatemala** (Done: #13)
- 🇭🇹 **Haiti** (Done: #14)
- 🇭🇳 **Honduras** (Done: #15)
- 🇲🇽 **Mexico** (Done: #16)
- 🇳🇮 **Nicaragua** (Done: #17)
- 🇵🇦 **Panama** (Done: #18)
- 🇵🇾 **Paraguay** (Done: #19)
- 🇵🇪 **Peru** (Done: #20)
- 🇩🇴 **Dominican Republic** (Done: #21)
- 🇺🇾 **Uruguay** (Done: #22)
- 🇻🇪 **Venezuela** (Done: #2)

**Comment by takayukister** [comment]
Congratulations! You've completed it! 🎉🎉🎉

The next major update of Listo including your lists will be released soon.
