### ISSUE TITLE
Listo 1.4 makes WooCommerce ignore translations

### ISSUE THREAD

**Issue by Bosphoramus** [rocklobster-in/listo#35]
Was updating a WordPress site to WP 5.9 and WooCommerce 6.2, noticed translations were being ignored by only WooCommerce, that means only the WooCommerce profile, Product detail page, review section lost translations it only shows in english.

Noticed it starts happening when updating listo from 1.3 to 1.4, when deactivating listo, translations start applying again.

**Comment by Bosphoramus** [comment]
Gonna downgrade to 1.3 for now

**Comment by takayukister** [comment]
**Warning:** GitHub isn't a place to post your support requests. Any support requests posted here will be closed without explanation. If you do it more than once, you will get blocked automatically.
