### ISSUE TITLE
Add a new filter hook to manipulate the list items easily

### ISSUE THREAD

**Issue by YordanSoares** [rocklobster-in/listo#62]
This user wanted to sort the items alphabetically when the items are translated: https://wordpress.org/support/topic/countries-list-4/#post-17283807

I shared this code snippet to them:

```php
/**
 * Listo (Contact Form 7):
 * Sort list items alphabetically
 */
function wpcf7_listo_lists_sort( $data, $options, $args ) {
	if ( is_array( $data ) ) {
		asort( $data );	
	}
	return $data;
}
add_filter( 'wpcf7_form_tag_data_option', 'wpcf7_listo_lists_sort', 11, 3 );
```

...but I think we could do it in this extension directly, to filter the lists easily.

**Comment by takayukister** [comment]
In #69, I added `orderby` and `order` options support. Set them in your `listo()` caller function.
